config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items, except: [:new, :create]
  resources :boxes do
     resources :items, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "boxes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/box.rb
class Box < ApplicationRecord
  has_many :items
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  has_rich_text :content

    def tag_list
        tag_ids
    end

    def tag_list=(input)
       input.each do |element|
          if element.to_i > 0
            self.tags << Tag.find_by!(id: element.to_i)
          else
            self.tags << Tag.create!(title: element)
          end
        end
    end
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :box
    has_one_attached :image
    
    validates_presence_of :title    
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user, optional: true
  has_many :taggings, dependent: :destroy
  has_many :boxes, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :box
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boxes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit::Authorization
    before_action :authenticate_user!

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: %i[ show edit update destroy ]

  # GET /boxes or /boxes.json
  def index
    @boxes = current_user.boxes
  end

  # GET /boxes/1 or /boxes/1.json
  def show
    authorize(@box)
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
    authorize(@box)
  end

  # POST /boxes or /boxes.json
  def create
    @box = Box.new(box_params)
    @box.user = current_user

    respond_to do |format|
      if @box.save
        format.html { redirect_to box_url(@box), notice: "Box was successfully created." }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1 or /boxes/1.json
  def update
    authorize(@box)
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to box_url(@box), notice: "Box was successfully updated." }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1 or /boxes/1.json
  def destroy
    authorize(@box)
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url, notice: "Box was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def box_params
      params.require(:box).permit(:bid, :description, :content, tag_list: [])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.where(boxes: current_user.boxes)
  end

  # GET /items/1 or /items/1.json
  def show
    authorize(@item)
  end

  # GET /items/new
  def new
    box = Box.find(params[:box-id])
    @item = Item.new(box: box)

    authorize(@item)
  end

  # GET /items/1/edit
  def edit
    authorize(@item)
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @item.box = Box.find(params[:box_id])

    authorize(@item)

    respond_to do |format|
      if @item.save
        format.html { redirect_to box_url(@item.box), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    authorize(@item)
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to box_url(@item.box), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    authorize(@item)
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :box_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/boxes/_box.html.erb
<div  class="card mb-2" id="<%= dom_id box %>">
  <%= link_to box_path(box) do %>
    <div class="card-content is-flex is-justify-content-space-between">
      <div>
        <span class="icon">
          <i class="fa-solid fa-box-open" aria-hidden="true"></i>
        </span>

        <%= box.bid %>
      </div>

      <div>
        <% box.tags.each do |tag| %>
          <span class="tag <%= tag.color %> ml-1">
            <%= tag.title %>
            <i class="<%= tag.icon %> ml-1"></i>
          </span>
        <% end %>
      </div>
    </div>
    
  <% end %>
</div>
     
  

app/views/boxes/_form.html.erb
<%= form_with(model: box) do |form| %>
  <% if box.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
        <% box.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bid, style: "display: block", class: "label" %>
    <div class="control">
      <%= form.text_field :bid, class: "input", placeholder: "Box name" %>
    </div>
  </div>

  <div class="select is-multiple  mb-4">
    <% accessible_tags = Tag.all.map { |t| [t.title, t.id] } %>
    <%= form.select :tag_list, accessible_tags,
      { multiple: true, include_blank: true },
      {"data-controller": "tom" }
    %>
  </div>

  <div class="field">
    <%= form.label :content, class: "label" %>
    <div class="control">
       <%= form.rich_text_area :content %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, style: "display: block", class: "label" %>
    <div class="control">
      <%= form.text_area :description, class: "textarea", placeholder: "Items" %>
    </div>
  </div>

  <div>
    <%= form.button "Create Item", class: "button is-primary"%>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render "form", box: @box %>

<br>

<div>
  <%= link_to "Show this box", @box, class: "button is-light" %> |
  <%= link_to "Back to boxes", boxes_path, class: "button is-light" %>
</div>

app/views/boxes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="is-size-1">Boxes</h1>

<div id="boxes" >
  <% @boxes.each do |box| %>
    <%= render "boxes/box", box: box %>
  <% end %>
</div>

<%= link_to "New box", new_box_path, class:"button is-primary mt-4" %>

app/views/boxes/new.html.erb
<h1 class="is-size-1">New box</h1>

<%= render "form", box: @box %>

<br>

<div>
  <%= link_to "Back to boxes", boxes_path, class:"button is-light" %>
</div>

app/views/boxes/show.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="is-size-1"><%= @box.bid %></h1>

<div class="content">
  <%= @box.content %>
</div>

<div class="box">
  <%= simple_format @box.description %>
</div>

<% @box.items.each do |i| %>
  <%= render "items/item", item: i %>
<% end %>

 <%= render "items/form", item: Item.new(box: @box), url: box_items_path(@box) %>

<div>
  <%= link_to "Edit this box", edit_box_path(@box), class: "button is-light"  %> 
  <%= link_to "Back to boxes", boxes_path, class: "button is-light" %>

  <%= button_to "Delete", @box, method: :delete, data: { turbo_confirm: "Si si isty?"}, class: "button is-danger mt-3" %>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, url: url, class: "box") do |form| %>
<%= form.hidden_field :box_id %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>

    <%= link_to "back to box", box_path(item.box) %>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label is-hidden" %>
    <%= form.text_field :title, class: "input", placeholder: "topanky" %>
  </div>
  
  
  <div class="is-flex">
    <div class="file has-name is-boxed" id="file-js-example">
      <label class="file-label">
        <%= form.file_field :image, class:"file-input"  %>
        <span class="file-cta">
          <span class="file-icon">
            <i class="fas fa-upload"></i>
          </span>
          <span class="file-label">
            Choose new image
          </span>
        </span>
        <span class="file-name">
          No file selected
        </span>
      </label>
    </div>

      <% if item.image.attached? %>
        <div class="ml-2">
        <strong>Current image</strong>
          <figure class="image is-128x128">
              <%= image_tag item.image.variant(resize_to_limit: [200, 200])  %>
          </figure>
        </div>     
      <% end %>
  </div>





<script>
  const fileInput = document.querySelector('#file-js-example input[type=file]');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('#file-js-example .file-name');
      fileName.textContent = fileInput.files[0].name;
    }
  }
</script>


  <div>
    <%= form.button "OK", class: "button is-primary"%>
    
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class="box is-flex is-justify-content" >
  <figure class="image is-96x96 mr-2">
    <% if item.image.attached? %>
      <%= image_tag item.image.variant(resize_to_limit: [100, 100])  %>
    <% else %>
        <%# <img src="https://placehold.co/200x200"> %>
        <%= image_tag "download.png" %>
    <% end %>
  </figure>

  <div class="is-flex is-justify-content-space-between is-flex-grow-2">
    <div>
      <div><%= item.title %></div>
        <% if controller_name == "items" %>
          <strong>
            <%= link_to item.box.bid, box_path(item.box) %>
          </strong> 
        <% end %>
    </div>

    <div>
      <%= link_to "Edit", edit_item_path(item), class:"button is-primary" %>
    </div>
  </div>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item, url: item_path(@item) %>


<div>
  <%= link_to "Show this item", @item, class: "button is-light" %> 
  <%= link_to "Back to items", items_path, class: "button is-light" %>
  <%= button_to "Delete", @item, method: :delete, data: { turbo_confirm: "Si si isty?"}, class: "button mt-2 is-danger " %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="is-size-1">Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render "items/item", item: item %>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="<%= boxes_path %>">
        Boxes
      </a>

      <%= link_to "Items", items_path, class:"navbar-item" %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    
    <div class="navbar-end">
      <div class="navbar-item">
        <% if current_user %>
          <%= current_user.email %>
          <%= link_to "Sign out", destroy_user_session_path, class:"button is-danger", data: {turbo_method: :delete} %>
        <% else %>
          <div class="buttons"> 
            <a class="button is-primary" href="/users/sign_up">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="<%= new_user_session_path %>">
               <strong>Log in</strong>
            </a>
          </div>
        <% end %>
      </div>
    </div> 
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css" rel="stylesheet">
   
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/nav" %>

    <div class="container">
      <% if alert %>
        <div class="notification is-danger">
          <button class="delete"></button>
          <%= alert %>
        </div>
      <% end %>

      <% if notice %>
        <div class="notification is-success">
          <button class="delete"></button>
          <%= notice %>
        </div>
      <% end %>
    </div>

    
      <p class="notice"></p>
      <p class="alert"></p>


    <section class="section">
      <div class="container">
      <%= yield %>
      </div>
    </section>
  </body>
</html>